INSERT IGNORE INTO Task (TaskDescription, Difficulty, PointReward)
VALUES ('Create a Snowball farm', 'Easy', 10),
       ('Create a Nether Portal', 'Easy', 15),
       ('Create a fully automatic Cactus farm', 'Easy', 15),
       ('Create a fully automatic Melon farm', 'Easy', 15),
       ('Create a fully automatic Pumpkin farm', 'Easy', 15),
       ('Create a fully automatic Sugar Cane farm', 'Easy', 15),
       ('Create a fully automatic Bamboo farm', 'Easy', 15),
       ('Create a fully automatic Red Mushroom farm', 'Easy', 15),
       ('Create a fully automatic Brown Mushroom farm', 'Easy', 15),
	   ('Create a full enchanting setup', 'Easy', 20),
       ('Create a fully automatic Chicken farm', 'Easy', 20),
       ('Breed 100 animals', 'Easy', 20),
       ('Mine 10,000 stone', 'Easy', 20),
       ('Create a fully automatic wheat farm', 'Easy', 20),
       ('Create a fully automatic carrot farm', 'Easy', 20),
       ('Create a fully automatic potato farm', 'Easy', 20),
       ('Create a fully automatic beetroot farm', 'Easy', 20),
       ('Create a Lava farm', 'Easy', 20),
       ('Create a Powdered Snow farm', 'Easy', 20),
       ('Roleplay as Steve Irwin for an entire episode', 'Easy', 20),
       ('Get a Skeleton Horse', 'Easy', 25),
       ('End every clip with a bad pun for an episode', 'Easy', 25),
       ('Start every clip with a bad signature catchphrase for an episode', 'Easy', 25),
       ('Create an experience farm from a dungeon spawner', 'Easy', 25),
       ('Host a gameshow for a game that you create', 'Easy', 25),
       ('Obtain a stack of every wood type, including the Nether', 'Easy', 25),
       ('Catch 100 Fish', 'Easy', 25),
       ('Create a fully automated Moss farm', 'Easy', 25),
       ('Get a villager that sells Mending books for 1 emerald each', 'Easy', 30),
       ('Give someone a stack of diamonds for nothing in return', 'Easy', 30),
       ('Create a fully automated Magma Cream farm', 'Easy', 30),
       ('Create an experience farm from any Spider spawner', 'Easy', 30),
       ('Create a fully automated Dripstone farm', 'Easy', 30),
       ('Get a Silk Touch diamond pickaxe', 'Easy', 30),
       ('Create an Enderman farm', 'Easy', 35),
       ('Create an experience farm from a Blaze spawner', 'Easy', 35),
       ('Get a Fortune III diamond pickaxe', 'Easy', 35),
       ('Get a Looting III diamond sword', 'Easy', 35),
       ('Trade with Villagers 100 times', 'Medium', 45),
       ('Create a Squid farm', 'Medium', 45),
       ('Create a Copper farm', 'Medium', 45),
       ('Make an episode into a pseudo movie with a plot and climax', 'Medium', 45),
	   ('Cure a naturally spawned Zombie Villager', 'Medium', 45),
       ('Create a fully automatic honeycomb farm using at least 15 bees', 'Medium', 45),
       ('Create a fully automatic wool farm for every color', 'Medium', 45),
       ('Create a fully automatic Slime farm', 'Medium', 50),
       ('Create a fully automatic Pork/Leather farm', 'Medium', 50),
       ('Travel 5km by Pig', 'Medium', 50),
       ('Win 30 Raids', 'Medium', 50),
       ('Create a Creeper farm', 'Medium', 50),
	   ('Create a fully automatic Iron farm', 'Medium', 50),
       ('Travel 5km by Strider', 'Medium', 55),
       ('Create a fully automatic Gold farm', 'Medium', 55),
       ('Create a fully automatic Wither Skeleton farm', 'Medium', 65),
       ('Create a fully automatic Guardian farm', 'Medium', 65),
       ('Create a Raid farm', 'Medium', 65),
       ('Create a Trident farm', 'Medium', 65),
       ('Create a Ghast farm', 'Medium', 70),
       ('Create a fully powered beacon', 'Hard', 80),
       ('Cave for an entire episode in Gold Armor without hitting a single mob', 'Hard', 80),
       ('Kill every hostile mob at least once', 'Hard', 85),
       ('Create 6 fully powered beacons to get every possible potion effect', 'Hard', 90),
       ('Create a fully automated Wither Rose farm', 'Hard', 95),
       ('Get an entire set of Netherite tools and armor, including a Netherite Hoe', 'Hard', 100),
       ('Visit every single biome', 'Hard', 110),
       ('Do not wear any armor until a full set of diamond armor is bought from villagers', 'Hard', 125),
       ('Get every max-level enchanted book available from villagers for one emerald each', 'Hard', 175),
       ('Defeat 4 Withers at once. No cheesing allowed', 'Hard', 250);