INSERT IGNORE INTO Task (TaskDescription, Difficulty, PointReward)
VALUES ('Create a Snowball farm', 'Easy', 10),
       ('Create a Nether Portal', 'Easy', 15),
       ('Create a fully automatic Cactus farm', 'Easy', 15),
       ('Create a fully automatic Melon farm', 'Easy', 15),
       ('Create a fully automatic Pumpkin farm', 'Easy', 15),
       ('Create a fully automatic Sugar Cane farm', 'Easy', 15),
       ('Create a fully automatic Bamboo farm', 'Easy', 15),
       ('Create a fully automatic Red Mushroom farm', 'Easy', 15),
       ('Create a fully automatic Brown Mushroom farm', 'Easy', 15),
	   ('Create a full enchanting setup', 'Easy', 20),
       ('Create a fully automatic Chicken farm', 'Easy', 20),
       ('Breed 100 animals', 'Easy', 20),
       ('Mine 10,000 stone', 'Easy', 20),
       ('Create a fully automatic Carrot farm', 'Easy', 20),
       ('Create a fully automatic Potato farm', 'Easy', 20),
       ('Create a fully automatic Beetroot farm', 'Easy', 20),
       ('Create a Lava farm', 'Easy', 20),
       ('Create a Powdered Snow farm', 'Easy', 20),
       ('Roleplay as Steve Irwin for an entire episode', 'Easy', 20),
       ('Obtain a Skeleton Horse', 'Easy', 25),
       ('End every clip with a bad pun for an episode', 'Easy', 25),
       ('Start every clip with a bad signature catchphrase for an episode', 'Easy', 25),
       ('Create an experience farm from a dungeon spawner', 'Easy', 25),
       ('Host a gameshow for a game that you create', 'Easy', 25),
       ('Obtain a stack of every wood type, including the Nether woods', 'Easy', 25),
       ('Catch 100 Fish', 'Easy', 25),
       ('Create a fully automatic Moss farm', 'Easy', 25),
       ('Get a villager that sells Mending books for 1 emerald each', 'Easy', 30),
       ('Give someone a stack of diamonds for nothing in return', 'Easy', 30),
       ('Create a fully automatic Magma Cream farm', 'Easy', 30),
       ('Create an experience farm from any Spider spawner', 'Easy', 30),
       ('Create a fully automatic Dripstone farm', 'Easy', 30),
       ('Get a Silk Touch diamond pickaxe', 'Easy', 30),
       ('Create an Enderman farm', 'Easy', 35),
       ('Create an experience farm from a Blaze spawner', 'Easy', 35),
       ('Get a Fortune III diamond pickaxe', 'Easy', 35),
       ('Get a Looting III diamond sword', 'Easy', 35),
       ('Trade with Villagers 100 times', 'Medium', 45),
       ('Create a Squid farm', 'Medium', 45),
       ('Create a Copper farm', 'Medium', 45),
       ('Make an episode into a pseudo movie with a plot and climax', 'Medium', 45),
	   ('Cure a naturally spawned Zombie Villager', 'Medium', 45),
       ('Create a fully automatic honeycomb farm using at least 15 bees', 'Medium', 45),
       ('Create a fully automatic wool farm for every color', 'Medium', 45),
       ('Create a fully automatic Slime farm', 'Medium', 50),
       ('Create a fully automatic Pork/Leather farm', 'Medium', 50),
       ('Travel 5km by Pig', 'Medium', 50),
       ('Win 30 Raids', 'Medium', 50),
       ('Create a Creeper farm', 'Medium', 50),
	   ('Create a fully automatic Iron farm', 'Medium', 50),
       ('Travel 5km by Strider', 'Medium', 55),
       ('Create a fully automatic Gold farm', 'Medium', 55),
       ('Create a fully automatic Wither Skeleton farm', 'Medium', 65),
       ('Create a fully automatic Guardian farm', 'Medium', 65),
       ('Create a Raid farm', 'Medium', 65),
       ('Create a Trident farm', 'Medium', 65),
       ('Create a Ghast farm', 'Medium', 70),
       ('Create a fully powered beacon', 'Hard', 80),
       ('Cave for an entire episode in Gold Armor without hitting a single mob', 'Hard', 80),
       ('Kill every hostile mob at least once', 'Hard', 85),
       ('Create 6 fully powered beacons to get every possible potion effect', 'Hard', 90),
       ('Create a fully automatic Wither Rose farm', 'Hard', 95),
       ('Get an entire set of Netherite tools and armor, including a Netherite Hoe', 'Hard', 100),
       ('Visit every single biome', 'Hard', 110),
       ('Do not wear any armor until a full set of diamond armor is bought from villagers', 'Hard', 125),
       ('Get every max-level enchanted book available from villagers for one emerald each', 'Hard', 175),
       ('Defeat 4 Withers at once. No cheesing allowed', 'Hard', 250),
       ('Obtain fully-enchanted Diamond Armor', 'Easy', 20),
       ('Have every crop growing at once', 'Easy', 25),
       ('Survive 10 creeper explosions in one night', 'Easy', 15),
       ('Kill the Enderdragon without missing a single arrow shot; 5 shots minimum required', 'Hard', 90),
       ('Survive a night outside using only fists', 'Easy', 20),
       ('Declare a villager King. Build them a manor, give them a prestigious job, and moving them in', 'Easy', 30),
       ('Create a village in the Nether', 'Easy', 35),
       ('Create a village in the End', 'Easy', 40),
       ('Transform a village to be Medieval', 'Easy', 35),
       ('Build 3 Iron Golems and create a mansion for them to live in', 'Easy', 20),
       ('You have become an Overworld zookeeper! Build a zoo and get all Overworld creatures, including hostile', 'Medium', 50),
       ('Create an aquarium or pond with all fish and glow squid', 'Easy', 20),
       ('Your grandpa Timmy left his legacy of cartography to you. Fulfill it by mapping out a 9*9 area on a map', 'Easy', 35),
       ('Host a sleepover for the server, complete with snacks, entertainment, and activities that will last until dawn', 'Easy', 20),
       ('With your refined taste in music, it would be embarrassing not to own a copy of every music disc', 'Medium', 50),
       ('Create your first iron pickaxe from iron received through an automatic iron farm', 'Medium', 55),
       ('Help a Zombie Village to revert to its glory days', 'Medium', 50),
       ('Hold a concert for the server', 'Easy', 25),
       ('Obtain an Iron Ingot', 'Progression', 2),
       ('Obtain a stack of Logs', 'Progression', 1),
       ('Obtain a Diamond', 'Progression', 6),
       ('Obtain a Gold Ingot', 'Progression', 4),
       ('Obtain a stack of food', 'Progression', 2),
       ('Obtain 5 stacks of Cobblestone', 'Progression', 2),
       ('Obtain 5 stacks of Cobbled Deepslate', 'Progression', 4),
       ('Obtain Obsidian', 'Progression', 7),
       ('Smelt a stack of Iron Chunks', 'Progression', 4),
       ('Obtain Bamboo', 'Progression', 4),
       ('Obtain Carrots', 'Progression', 2),
       ('Obtain Potatoes', 'Progression', 2),
       ('Obtain Beetroot', 'Progression', 2),
       ('Obtain Moss', 'Progression', 5),
       ('Smelt a stack of Gold Chunks', 'Progression', 9),
       ('Obtain a stack of Diamonds', 'Progression', 18),
       ('Brew a potion', 'Progression', 5),
       ('Obtain an Elytra', 'Progression', 15),
       ('Obtain a Copper Ingot', 'Progression', 1),
       ('Smelt a stack of Copper Chunks', 'Progression', 2),
       ('Obtain Coal', 'Progression', 1),
       ('Obtain a stack of Coal', 'Progression', 2),
       ('Craft a Shulker Box', 'Progression', 12),
       ('Obtain an Ender Pearl', 'Progression', 3),
       ('Craft an Ender Chest', 'Progression', 9),
       ('Obtain 4 stacks of Clay Balls', 'Progression', 2),
       ('Obtain Stone', 'Progression', 1),
       ('Obtain a full set of Iron Armor', 'Progression', 5),
       ('Obtain an Axolotl', 'Progression', 3),
       ('Obtain a stack of Dirt', 'Progression', 1),
       ('Obtain a stack of Sand', 'Progression', 1),
       ('Obtain Redstone', 'Progression', 3),
       ('Obtain a stack of Redstone', 'Progression', 5),
       ('Obtain Lapis Lazuli', 'Progression', 3),
       ('Obtain a stack of Lapis Lazuli', 'Progression', 5),
       ('Obtain an Emerald', 'Progression', 2),
       ('Obtain an enchanting table', 'Progression', 8),
       ('Obtain 15 bookshelves', 'Progression', 5),
       ('Obtain Chorus Fruit', 'Progression', 10),
       ('Obtain Quartz', 'Progression', 4),
       ('Obtain Cocoa Beans', 'Progression', 5),
       ('Obtain a Grass Block', 'Progression', 4),
       ('Obtain a Heart of the Sea', 'Progression', 2),
       ('Obtain 8 Nautilus Shells', 'Progression', 15),
       ('Craft an Eye of Ender', 'Progression', 5),
       ('Obtain an Amethyst Shard', 'Progression', 2),
       ('Obtain a Wither Skeleton Head', 'Progression', 10),
       ('Obtain a Cactus', 'Progression', 2),
       ('Obtain a Vine', 'Progression', 2),
       ('Obtain a Glow Lichen', 'Progression', 2),
       ('Create an automatic Shulker Farm', 'Hard', 105),
       ('Befriend an animal', 'Progression', 3),
       ('Obtain one of every mob head', 'Medium', 70),
       ('Create a Villager breeder', 'Easy', 25);