name: HeretechsUtil
version: 0.1
main: me.heretechsutil.HeretechsUtil
api-version: 1.17
author: FleetingDream

#commands
commands:
  points:
    description: pay a player or query your points
    usage: /<command> [pay/query] <player> <points>
    default: true
    aliases: [p]
