name: HeretechsUtil
version: 0.1
main: me.heretechsutil.HeretechsUtil
api-version: 1.17
author: FleetingDream

#commands
commands:
  pay:
    description: pay a player in points
    usage: /<command> <player> <points>
    aliases: [pp]
